### PR TITLE
Move ws-python to ws-python-django

### PR DESCRIPTION
**Pull request by jdloft**
Django isn't Python. It makes more sense to have `-django` appended because it shows that it isn't regular Python.

### CODE REVIEW

**Comment by justin8** [comment]
This is why it shows as python and django in the UI. Changing the image name now would require a lot of work, and only be visible on the backend. I wish we'd chosen the correct names at the start, but that is why we have contribution guidelines now :)

**Comment by jdloft** [comment]
Understood. Do you know when the Django k logo is going to show up on C9.io? It's present in this repo but isn't shown there.

**Comment by justin8** [comment]
I made a PR for that the other day, it should be out soon; the wrong logo there was a mistake.

**Comment by jdloft** [comment]
Okay.

**Pull request closed without merging**
