### PR TITLE
Upgrade Ruby to 2.3.4 and Rails to 5.1.0.rc2

### PR DESCRIPTION
**Pull request by lachlanjc**
Previously the Rails template used ruby@2.3.0 + rails@4.2.5, so this PR upgrades them both to the latest versions. :new:

### CODE REVIEW

**Comment by justin8** [comment]
Sorry it took so long to get back to you here. I added 2.3.4 to the test, and updated the default non-rails-5 release to use 2.3.4 as well.

**Comment by justin8** [comment]
Closing in favour of #76

**Comment by lachlanjc** [comment]
@javruben Sure thing. Any reason not to use Rails 5?

**Comment by justin8** [comment]
Originally the split was because 5.x wasn't stable yet, we wanted the default rails to be the latest stable. But you're right, it should probably just be 5 now

**Pull request closed without merging**
