### PR TITLE
[DO NOT MERGE] Node update

### PR DESCRIPTION
**Pull request by justin8**
Need to fix issue with tests failing due to this bug first:
https://github.com/npm/npm/issues/9863

### CODE REVIEW

**Comment by frank-dspeed** [comment]
Add that process all will work like a charm

RUN cd $(npm root -g)/npm \
 && npm install fs-extra \
 && sed -i -e s/graceful-fs/fs-extra/ -e s/fs\.rename/fs.move/ ./lib/utils/rename.js

**Comment by justin8** [comment]
Yeah, I need more thorough testing of that first. Reinstalling or updating npm will disable that fix and break it again in the workspaces, so I'm a bit hesitant to apply it just yet.

**Comment by frank-dspeed** [comment]
ehm your wrong look your building a docker image so this gets executed on every build of that.
if you have anything in your container startet from that image that updates npm inside it.
your wrong!!! you need to create a new dockerimage on every new nodejs + npm version you should never update that insde the runing container!!!!

**Comment by frank-dspeed** [comment]
Also a idea if you realy need to update npm inside of a container based on a image with other npm version you should simply add a patchNPM execute able that executes the commands and your done the patch is compatible to all NPM versions that have the issu

**Comment by timjrobinson** [comment]
@frank-dspeed I'm not sure you understand how Cloud9 works. We create docker containers for our users that they control completely. We give them a base image and they can install / upgrade whatever they like on top of that. If they want to upgrade NPM they need to be able to.

We could monkey patch npm upgrading, but would rather fix the underlying cause because hacks will always come back to bite us in the future.

**Comment by frank-dspeed** [comment]
@timjobinson but thats against docker principals thats not what docker is made for its not a vm replacement.
Wouldnt it be more good tomake your image work on a ONBUILD base better? so the users can choose to simply use what ever base image they like for example node:5.6 node 6.0 and you check inyour onbuild instructions whats there whats not and then add your stuff via ONBUILD commands to the used baseimage what ever it is ?

So your users can still stream upgrade the workspace via a new baseimage?

**Comment by frank-dspeed** [comment]
Or other alternate is to supply dockerimages with diffrent pachted nodejs version installed you could use stackbrew or the other technics used to make offical docker images you find good examples how to use template files to build diffrent image versions from your base.

**Comment by frank-dspeed** [comment]
Sorry that i comment here so much but docker is simply made to build a static environment and if you whant to update anything in that you update the baseimage all other is not deploy  able via registrys and not as reuseable as it should be its realy against the concepts thats why i care because people could adapt your workflow like they did with this evil GitHub - phusion/baseimage-docker: A minimal Ubuntu base image .

**Comment by frank-dspeed** [comment]
Oh Sorry and last alternate info only to drive you forward the npm relase cant address this issu in current state a fix for that is expect not expected till end next year. The problem is that npm trys to stay fast on all environments and can't single address the docker issu it neds to get fixed on docker side docker itself has no issu its the way it works so you see.

But the problem will be solved as soon as NPM finishes its restructuring to a extra build tree but that will take a year or more and so not will be docker frindly because the file layers docker uses if you then fire a row of npm commands it could lead to bigger images if you dont clean up right.

**Pull request closed without merging**
